version: 1

aws:
  default_region: ap-south-1

instances:
  raptor-catalog:
    db_instance_identifier: cleancatalograptorsupplies
    secret_id: infra-auditor/postgres/raptor-catalog

  udb:
    db_instance_identifier: udb
    secret_id: infra-auditor/postgres/udb
